version: '3.2'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker_volumes/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  php1:
    build: frontend
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql

  php2:
    build: frontend
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/etc/nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf
      # - ./nginx/etc/nginx/ssl/:/etc/nginx/ssl
      - ./nginx/runtime/logs/nginx:/var/log/nginx
      # Mount source-code for development
      - ./:/app
    depends_on:
      - php1
      - php2
